# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os: linux
dist: xenial
repos:
  CRAN: https://cloud.r-project.org
  PIK:  https://rse.pik-potsdam.de/r/packages/
cache: packages
latex: true
pandoc: true
r_packages:
  - covr
  - qgraph
  - devtools
  - testthat
  - lucode
script:
  - Rscript -e 'devtools::test()'
after_success:
  - Rscript -e 'covr::codecov()'
